### ISSUE TITLE
sessionInfo() and/or R package versions?

### ISSUE THREAD

**Issue by RegnerM2015** [corceslab/ATAC_IterativeOverlapPeakMerging#1]
Hi @rcorces and @fiorella-grandi,

I was wondering what specific versions of R packages were used during the making of this script? 

I received an error about GenomicRangesList being "defunct". Do you know what specific version of GenomicRanges was used? 

Thanks!

**Comment by rcorces** [comment]
Thats unfortunate. Looks like that happened here:
https://github.com/Bioconductor/GenomicRanges/commit/ccbb444c49e41b5ccd394968540c70fb9cf06981

**Comment by RegnerM2015** [comment]
I think we resolved this issue by installing an older version of GenomicRanges. Thanks!

**Comment by agehrke6** [comment]
> I think we resolved this issue by installing an older version of GenomicRanges. Thanks!

@RegnerM2015 Do you know what version you got to work?

**Comment by rcorces** [comment]
@agehrke6 - `GenomicRanges v 1.42.0` should work.

**Comment by agehrke6** [comment]
Just FYI I got it working with GenomicRanges 1.44.0, what I did was simply replace all instances of "GenomicRangesList" with "GRangesList" in the R script. Might work with GenomicRanges v 1.48.0 using the same strategy but I havent tried.

**Comment by rcorces** [comment]
Thanks @agehrke6
I've gone ahead and made that change via https://github.com/corceslab/ATAC_IterativeOverlapPeakMerging/commit/ac17428902e7d9b84f49c9019395d5f9e5c04562

This has been merged into main and created as a new release tag `v1.1.0`
