### ISSUE TITLE
GenomicRangeList error

### ISSUE THREAD

**Issue by agehrke6** [corceslab/ATAC_IterativeOverlapPeakMerging#2]
Really excited to use this strategy, but I keep getting the following error:

Error: 'GenomicRangesList' is not an exported object from 'namespace:GenomicRanges'
Execution halted

Any chance you can help? Thanks very much

**Comment by rcorces** [comment]
This was posted about previously here - https://github.com/corceslab/ATAC_IterativeOverlapPeakMerging/issues/1
Its a GenomicRanges version problem. Some of the features used in our script have been deprecated in more recent versions and I havent had a chance to update it.

**Comment by agehrke6** [comment]
Sorry about that I missed it, will try an older version thanks
