### ISSUE TITLE
chrY in union peak set

### ISSUE THREAD

**Issue by katecycho** [corceslab/ATAC_IterativeOverlapPeakMerging#4]
Hello,

Thank you for sharing this useful script, it's been very helpful in generating union peak set.
I have successfully ran your code, but I noticed that peaks from chrY are still left in the peak set files (* .filter.non_overlapping.bed). I can filter them out manually but not sure if there is an issue in the code. I have generated summits.bed files from narrowPeak files (generated using ENCODE pipeline) and ran the code with default settings. 

Thank you!

**Comment by rcorces** [comment]
That does seem surprising. I'll try to look into this next week. Thanks for reporting.

**Comment by rcorces** [comment]
Hi @katecycho 
I'm unfortunately not able to replicate this issue. `chrY` is appropriately removed from my file peak set file `All_Samples.fwp.filter.non_overlapping.bed`.

If you want to dig deeper, you are welcome to. I would start by testing the `removeSpecificChromosome()` function from this line on a `GRanges` object that you have.

https://github.com/corceslab/ATAC_IterativeOverlapPeakMerging/blob/06205e5284e91959607304206ee5df178cf643b0/createIterativeOverlapPeakSet.R#L380

Feel free to post again here if you want to troubleshoot. I'm going to close the issue for keeping track of things but am happy to reopen it if you find anything on your end.
