### ISSUE TITLE
using output of Genrich or MACS3 (HMMRATAC) for the merging

### ISSUE THREAD

**Issue by sunta3iouxos** [corceslab/ATAC_IterativeOverlapPeakMerging#7]
Hi, all,
what should I do to get the output of the other 2 popular peak callers for ATAC-seq, meaning how can I change the output of the peakcallers to fit the MACS2 default option?
Genrich provides an IDR type of significance [estimation](https://github.com/jsh58/Genrich?tab=readme-ov-file#multiple-replicates), so I do not think that this is nescessary to be calculated, but as far as I knoe MACS3-HMMRATAC do not.

Thank you!

**Comment by rcorces** [comment]
This code is not designed to handle other types of input. If you use a different peak caller, the expectation would be that you adapt the output of that peak caller to fit the expected input format for this code (macs2 summit files).
